reembolsos/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import URLPattern, path, include
from django.conf.urls.static import static

from . import views

admin.site.site_header = 'Admin Sys - NAF'
admin.site.site_title = 'Admin Sys - NAF'
admin.site.index_title = 'Administração do Sistema'

urlpatterns = [
    path('', views.index, name='index'),
    path('reembolso', views.reembolso, name='reembolso'),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

sysnaf/urls.py
from django.contrib import admin
from django.urls import path, re_path, include

from . import views

urlpatterns = [
    path('', include('reembolsos.urls')),
    path('usuarios/', include('usuarios.urls')),
    path('admin/', admin.site.urls),

    re_path(r'^$', views.IndexView.as_view(), name="index_url"),

    path('users/', include('users.urls', namespace="users")),
]

users/urls.py
from django.urls import re_path, path 
from . import views

app_name = "users"


urlpatterns = [
   	# Login, Register, Forgot password, Logout
    re_path(r'^login/$', views.LoginView.as_view(), name="login_url"),
    re_path(r'^register/$', views.RegisterView.as_view(), name="register_url"),
    re_path(r'^forgot-password/$', views.ForgotPasswordView.as_view(), name="forgot_password_url"),
    re_path(r'^logout/$', views.LogoutView.as_view(), name="logout_url"),

    re_path(r'^charts/$', views.ChartsView.as_view(), name="charts_url"),

    re_path(r'^tables/$', views.TablesView.as_view(), name="tables_url"),

    re_path(r'^buttons/$', views.ButtonsView.as_view(), name="buttons_url"),

    re_path(r'^cards/$', views.CardsView.as_view(), name="cards_url"),

	re_path(r'^page_not_found/$', views.PageNotFoundView.as_view(), name="page_not_found_url"),    

	re_path(r'^blank/$', views.BlankView.as_view(), name="blank_page_url"),    

	# Utilities
	re_path(r'^colors/$', views.ColorsView.as_view(), name="colors_url"),    

	re_path(r'^borders/$', views.BordersView.as_view(), name="borders_url"),    

	re_path(r'^animations/$', views.AnimationsView.as_view(), name="animations_url"),    

	re_path(r'^others/$', views.OthersView.as_view(), name="others_url"),    

]

usuarios/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('cadastro', views.cadastro, name='cadastro'),
    path('login', views.login, name='login'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('logout', views.logout, name='logout'),
]

reembolsos/models.py
from django.db import models
from datetime import datetime


class Reembolso(models.Model):
    nome = models.CharField(max_length=200)
    email = models.CharField(max_length=100)
    data_cadastro = models.DateTimeField(default=datetime.now, blank=True)
    data_servico = models.DateField()
    hora_servico = models.CharField(max_length=20)
    alimentacao = models.BooleanField(default=False)
    combustivel = models.BooleanField(default=False)
    enviado = models.BooleanField(default=False)
    memoria_atend = models.FileField(
        upload_to='memorias_atendimento/%Y/%m/%d/', blank=True)
    rota1 = models.CharField(max_length=200, blank=True, null=True)
    rota2 = models.CharField(max_length=200, blank=True, null=True)
    rota3 = models.CharField(max_length=200, blank=True, null=True)
    rota4 = models.CharField(max_length=200, blank=True, null=True)
    rota5 = models.CharField(max_length=200, blank=True, null=True)

    class Meta:
        db_table = "reembolso"

users/models.py
from django.db import models

# Create your models here.

usuarios/models.py
from django.db import models

# Create your models here.

reembolsos/views.py
from django.shortcuts import render

# Create your views here.
from multiprocessing import context
from turtle import title
from django.shortcuts import render

import reembolsos
from reembolsos.models import Reembolso
from .models import Reembolso


def index(request):
    return render(request, 'index.html')


def reembolso(request):
    reembolsos = Reembolso.objects.order_by('-data_cadastro').all()

    nome = request.GET.get('busca')

    if nome != '' and nome is not None:
        reembolsos = reembolsos.filter(nome=nome)

    dados = {
        'reembolsos': reembolsos
    }

    return render(request, 'reembolso.html', dados)

sysnaf/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response


class IndexView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/index.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})

users/views.py
from django.shortcuts import render
from rest_framework.views import APIView
from rest_framework.response import Response


class LoginView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/login.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class RegisterView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/register.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ForgotPasswordView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/forgot-password.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class LogoutView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/forgot-password.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ChartsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/charts.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class TablesView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/tables.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class LogoutView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/forgot-password.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ButtonsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/buttons.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class CardsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/cards.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class PageNotFoundView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/404.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class BlankView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/blank.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class ColorsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-color.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class BordersView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-border.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class AnimationsView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-animation.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})


class OthersView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "theme/utilities-other.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})



class DashboardView(APIView):
    def get(self, request, *args, **kwargs):
        return render(request, "users/dashboard.html", {})

    def post(self, request, *args, **kwargs):

        return Response({'status': 200})

usuarios/views.py
from django.shortcuts import render


def cadastro(request):
    return render(request, 'usuarios/cadastro.html')


def login(request):
    return render(request, 'usuarios/login.html')


def dashboard(request):
    return render(request, 'usuarios/dashboard.html')


def logout(request):
    return render(request, 'usuarios/logout.html')

ui/templates/cadastro-reembolso.html
{% extends 'base_x.html' %}
{% load static %}

{% block title %} Catastro Reembolso {% endblock %}

{% block container %}
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <!--
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                -->
                <div class="col-lg-8 offset-lg-2">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create An Account!</h1>
                        </div>
                        <form class="user">
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="first_name">First name</label>
                                    <input type="text" class="form-control form-control-user" id="first_name"
                                        placeholder="First Name" value="Wes">
                                </div>
                                <div class="col-sm-6">
                                    <label for="last_name">Last name</label>
                                    <input type="text" class="form-control form-control-user" id="last_name"
                                        placeholder="Last Name" value="McKinney">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control form-control-user" id="email"
                                    placeholder="Email Address" value="wes@gmail.com">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control form-control-user" id="password"
                                        placeholder="Password" value="Wes@123">
                                </div>
                                <div class="col-sm-6">
                                    <label for="conf_password">Confirm Password</label>
                                    <input type="password" class="form-control form-control-user" id="conf_password"
                                        placeholder="Repeat Password" value="Wes@123">
                                </div>
                            </div>
                            <a href="{% url 'users:login_url' %}" class="btn btn-primary btn-user btn-block">
                                Register Account
                            </a>
                            <hr>
                            <a href="{% url 'index_url' %}" class="btn btn-google btn-user btn-block">
                                <i class="fab fa-google fa-fw"></i> Register with Google
                            </a>
                            <a href="{% url 'index_url' %}" class="btn btn-facebook btn-user btn-block">
                                <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                            </a>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:forgot_password_url' %}">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:login_url' %}">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %}
<script type="text/javascript">
    $(document).ready(function () {
        $('.register-top-right-link').addClass('active-nav-link-x')
    })
</script>
{% endblock %}

ui/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Index{% endblock %}

{% block container_fluid %}
<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-4 text-gray-800">Index</h1>

</div>
{% endblock %}

ui/templates/theme/blank.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Blank {% endblock %}

{% block container_fluid %}
<div class="container-fluid">

	<!-- Page Heading -->
	<h1 class="h3 mb-4 text-gray-800">Blank Page</h1>

</div>
{% endblock %}

ui/templates/theme/components/navbar_x.html
{% load static %}

<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
    <div class="d-none d-sm-inline-block mr-auto ml-md-3 my-2 my-md-0 mw-100">
        <img class="img-responsive" src="{% static 'resource/logos/hygull_bg_1a1b1a.png' %}" id='site-logo-x'>
    </div>

    <!-- Topbar Navbar -->
    <ul class="navbar-nav ml-auto">
        <!-- Nav Item - Alerts -->
        <li class="nav-item dropdown no-arrow mx-1 data-top-right-link login-top-right-link">
            <a class="nav-link dropdown-toggle" href="{% url 'users:login_url' %}" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Login</span>
                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">
                    <i class="fas fa-sign-in-alt fa-fw"></i>
                </span>
            </a>
        </li>

        <li class="nav-item dropdown no-arrow mx-1 data-top-right-link register-top-right-link">
            <a class="nav-link dropdown-toggle" href="{% url 'users:register_url' %}" id="alertsDropdown" role="button"
                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span>Register</span>

                <!-- Counter - Alerts -->
                <span class="badge badge-danger badge-counter">
                    <i class="fas fa-user-plus fa-fw"></i>
                </span>
            </a>
        </li>
    </ul>
</nav>

ui/templates/theme/components/sidebar.html
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="{% url 'index_url' %}">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3"> {{WEBSITE_TOP_LEFT_NAME}}<sup>x</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="{% url 'index_url' %}">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Heading -->
  <div class="sidebar-heading">
    Administrativo
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseServicos" aria-expanded="true"
      aria-controls="collapseServicos">
      <i class="fas fa-fw fa-cog"></i>
      <span>Serviços</span>
    </a>
    <div id="collapseServicos" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Menu:</h6>
        <a class="collapse-item" href="{% url 'reembolso' %}">Lista Reembolso</a>
        <a class="collapse-item" href="{% url 'users:cards_url' %}">Cards</a>
        <a class="collapse-item" href="{% url 'users:buttons_url' %}">Buttons</a>
      </div>
    </div>
  </li>
  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <div class="sidebar-heading">
    Configurações
  </div>
  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true"
      aria-controls="collapseTwo">
      <i class="fas fa-fw fa-cog"></i>
      <span>Configurações</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Menu</h6>
        <a class="collapse-item" href="{% url 'cadastro' %}">Cadastro de Usuários</a>
        <a class="collapse-item" href="{% url 'users:cards_url' %}">Cards</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
      aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Utilities</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Utilities:</h6>
        <a class="collapse-item" href="{% url 'users:colors_url' %}">Colors</a>
        <a class="collapse-item" href="{% url 'users:borders_url' %}">Borders</a>
        <a class="collapse-item" href="{% url 'users:animations_url' %}">Animations</a>
        <a class="collapse-item" href="{% url 'users:others_url' %}">Other</a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Nav Item - Utilities Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true"
      aria-controls="collapseUtilities">
      <i class="fas fa-fw fa-wrench"></i>
      <span>Utilities</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Utilities:</h6>
        <a class="collapse-item" href="{% url 'users:colors_url' %}">Colors</a>
        <a class="collapse-item" href="{% url 'users:borders_url' %}">Borders</a>
        <a class="collapse-item" href="{% url 'users:animations_url' %}">Animations</a>
        <a class="collapse-item" href="{% url 'users:others_url' %}">Other</a>
      </div>
    </div>
  </li>



  <!-- Heading -->
  <div class="sidebar-heading">
    Addons
  </div>

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true"
      aria-controls="collapsePages">
      <i class="fas fa-fw fa-folder"></i>
      <span>Pages</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Login Screens:</h6>
        <a class="collapse-item" href="{% url 'users:login_url' %}">Login</a>
        <a class="collapse-item" href="{% url 'users:register_url' %}">Register</a>
        <a class="collapse-item" href="{% url 'users:forgot_password_url' %}">Forgot Password</a>
        <div class="collapse-divider"></div>
        <h6 class="collapse-header">Other Pages:</h6>
        <a class="collapse-item" href="{% url 'users:page_not_found_url' %}">404 Page</a>
        <a class="collapse-item" href="{% url 'users:blank_page_url' %}">Blank Page</a>
      </div>
    </div>
  </li>

  <!-- Nav Item - Charts -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:charts_url' %}">
      <i class="fas fa-fw fa-chart-area"></i>
      <span>Charts</span></a>
  </li>

  <!-- Nav Item - Tables -->
  <li class="nav-item">
    <a class="nav-link" href="{% url 'users:tables_url' %}">
      <i class="fas fa-fw fa-table"></i>
      <span>Tables</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>

ui/templates/theme/forgot-password.html
{% extends 'base_x.html' %}
{% load static %}


{% block title %} Forgot password {% endblock %}


{% block container %}
<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <!--
                            <div class="col-lg-6 d-none d-lg-block bg-password-image"></div>
                            -->
                        <div class="col-lg-8 offset-lg-2">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
                                    <p class="mb-4">We get it, stuff happens. Just enter your email address below and we'll send you a link to reset your password!</p>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <label for="email">Email Address</label>
                                        <input type="email" class="form-control form-control-user" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                    </div>
                                    <a href="{% url 'users:login_url' %}" class="btn btn-primary btn-user btn-block">
                                    Reset Password
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:register_url' %}">Create an Account!</a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:login_url' %}">Already have an account? Login!</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

ui/templates/theme/login.html
{% extends 'base_x.html' %}
{% load static %}

{% block title %} Login {% endblock %}

{% block container %}

<div class="container">
    <!-- Outer Row -->
    <div class="row justify-content-center">
        <div class="col-xl-10 col-lg-12 col-md-9">
            <div class="card o-hidden border-0 shadow-lg my-5">
                <div class="card-body p-0">
                    <!-- Nested Row within Card Body -->
                    <div class="row">
                        <!--
                          <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                        -->
                        <div class="col-lg-8 offset-lg-2">
                            <div class="p-5">
                                <div class="text-center">
                                    <h1 class="h4 text-gray-900 mb-4">Welcome Back!</h1>
                                </div>
                                <form class="user">
                                    <div class="form-group">
                                        <label for="email">Email</label>
                                        <input type="email" class="form-control form-control-user" id="email" aria-describedby="emailHelp" placeholder="Enter Email Address...">
                                    </div>
                                    <div class="form-group">
                                        <label for="password">Password</label>
                                        <input type="password" class="form-control form-control-user" id="password" placeholder="Password">
                                    </div>
                                    <div class="form-group">
                                        <div class="custom-control custom-checkbox small">
                                            <input type="checkbox" class="custom-control-input" id="customCheck">
                                            <label class="custom-control-label" for="customCheck">Remember Me</label>
                                        </div>
                                    </div>
                                    <a href="{% url 'index_url' %}" class="btn btn-primary btn-user btn-block">
                                      Login
                                    </a>
                                    <hr>
                                    <a href="{% url 'index_url' %}" class="btn btn-google btn-user btn-block">
                                    <i class="fab fa-google fa-fw"></i> Login with Google
                                    </a>
                                    <a href="{% url 'index_url' %}" class="btn btn-facebook btn-user btn-block">
                                    <i class="fab fa-facebook-f fa-fw"></i> Login with Facebook
                                    </a>
                                </form>
                                <hr>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:forgot_password_url' %}">
                                      Forgot Password?
                                    </a>
                                </div>
                                <div class="text-center">
                                    <a class="small" href="{% url 'users:register_url' %}">  Create an Account!
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %}
  <script type="text/javascript">
      $(document).ready(function() {
          $('.login-top-right-link').addClass('active-nav-link-x')
      })
  </script>
{% endblock %}

ui/templates/theme/register.html
{% extends 'base_x.html' %}
{% load static %}

{% block title %} Register {% endblock %}

{% block container %}
<div class="container">
    <div class="card o-hidden border-0 shadow-lg my-5">
        <div class="card-body p-0">
            <!-- Nested Row within Card Body -->
            <div class="row">
                <!--
                    <div class="col-lg-5 d-none d-lg-block bg-register-image"></div>
                -->
                <div class="col-lg-8 offset-lg-2">
                    <div class="p-5">
                        <div class="text-center">
                            <h1 class="h4 text-gray-900 mb-4">Create An Account!</h1>
                        </div>
                        <form class="user">
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="first_name">First name</label>
                                    <input type="text" class="form-control form-control-user" id="first_name" placeholder="First Name" value="Wes">
                                </div>
                                <div class="col-sm-6">
                                    <label for="last_name">Last name</label>
                                    <input type="text" class="form-control form-control-user" id="last_name" placeholder="Last Name" value="McKinney">
                                </div>
                            </div>
                            <div class="form-group">
                                <label for="email">Email</label>
                                <input type="email" class="form-control form-control-user" id="email" placeholder="Email Address" value="wes@gmail.com">
                            </div>
                            <div class="form-group row">
                                <div class="col-sm-6 mb-3 mb-sm-0">
                                    <label for="password">Password</label>
                                    <input type="password" class="form-control form-control-user" id="password" placeholder="Password" value="Wes@123">
                                </div>
                                <div class="col-sm-6">
                                    <label for="conf_password">Confirm Password</label>
                                    <input type="password" class="form-control form-control-user" id="conf_password" placeholder="Repeat Password" value="Wes@123">
                                </div>
                            </div>
                            <a href="{% url 'users:login_url' %}" class="btn btn-primary btn-user btn-block">
                            Register Account
                            </a>
                            <hr>
                            <a href="{% url 'index_url' %}" class="btn btn-google btn-user btn-block">
                              <i class="fab fa-google fa-fw"></i> Register with Google
                            </a>
                            <a href="{% url 'index_url' %}" class="btn btn-facebook btn-user btn-block">
                              <i class="fab fa-facebook-f fa-fw"></i> Register with Facebook
                            </a>
                        </form>
                        <hr>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:forgot_password_url' %}">Forgot Password?</a>
                        </div>
                        <div class="text-center">
                            <a class="small" href="{% url 'users:login_url' %}">Already have an account? Login!</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block js_body %}
  <script type="text/javascript">
      $(document).ready(function() {
          $('.register-top-right-link').addClass('active-nav-link-x')
      })
  </script>
{% endblock %}

ui/templates/users/dashboard.html
<!--Write your own-->

ui/templates/users/forgot_password.html
<!--Write your own-->

ui/templates/users/login.html
<!--Write your own-->

ui/templates/users/signup.html
<!--Write your own-->